# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "w00tify"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Paul Gallagher"]
  s.date = "2012-02-26"
  s.description = "rails 3 view helpers for services from google, facebook, twitter, uservoice .."
  s.email = "gallagher.paul@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "lib/w00tify.rb",
    "lib/w00tify/action_view_extensions.rb",
    "lib/w00tify/facebook/facebook_helper.rb",
    "lib/w00tify/google/analytics_helper.rb",
    "lib/w00tify/google/maps_helper.rb",
    "lib/w00tify/twitter/twitter_helper.rb",
    "lib/w00tify/uservoice/uservoice_helper.rb",
    "lib/w00tify/version.rb",
    "test/facebook/facebook_test.rb",
    "test/google/analytics_test.rb",
    "test/google/maps_test.rb",
    "test/test_helper.rb",
    "test/twitter/twitter_test.rb",
    "test/uservoice/uservoice_test.rb",
    "test/w00tify_test.rb",
    "w00tify.gemspec"
  ]
  s.homepage = "http://github.com/tardate/w00tify"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "collection of webby helpers"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["> 3.0.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.11"])
      s.add_development_dependency(%q<rake>, ["~> 0.9.2.2"])
    else
      s.add_dependency(%q<rails>, ["> 3.0.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rdoc>, ["~> 3.11"])
      s.add_dependency(%q<rake>, ["~> 0.9.2.2"])
    end
  else
    s.add_dependency(%q<rails>, ["> 3.0.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rdoc>, ["~> 3.11"])
    s.add_dependency(%q<rake>, ["~> 0.9.2.2"])
  end
end

